<%@ Page Title="" Language="C#" MasterPageFile="~/master2.Master" AutoEventWireup="true" CodeBehind="my booking.aspx.cs" Inherits="cp.WebForm14" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
 

    <style type="text/css">
        .auto-style1 {
            width: 88%;
            position: absolute;
            top:65%;
            left:5%;
            
            
            
        }
    </style>
 

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContentPlaceHolder3" runat="server">
    
    <div class="w3-center">
    
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CellPadding="4" DataSourceID="bookeddetails" ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="True" CssClass="auto-style1" Font-Bold="True">
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <Columns>
            <asp:BoundField DataField="Location" HeaderText="Location" SortExpression="Location" />
            <asp:BoundField DataField="Parking_Area" HeaderText="Parking_Area" SortExpression="Parking_Area" />
            <asp:BoundField DataField="Date_From" HeaderText="Date_From" SortExpression="Date_From" />
            <asp:BoundField DataField="Date_To" HeaderText="Date_To" SortExpression="Date_To" />
            <asp:BoundField DataField="Parking_Stand" HeaderText="Parking_Stand" SortExpression="Parking_Stand" />
            <asp:BoundField DataField="Car_Name" HeaderText="Car_Name" SortExpression="Car_Name" />
            <asp:BoundField DataField="Car_Number" HeaderText="Car_Number" SortExpression="Car_Number" />
            <asp:BoundField DataField="Total_Cost" HeaderText="Total_Cost" SortExpression="Total_Cost" />
        </Columns>
        <EditRowStyle BackColor="#999999" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#E9E7E2" />
        <SortedAscendingHeaderStyle BackColor="#506C8C" />
        <SortedDescendingCellStyle BackColor="#FFFDF8" />
        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
    </asp:GridView>

    </div>

    <asp:SqlDataSource ID="bookeddetails" runat="server" ConnectionString="<%$ ConnectionStrings:Online Car Parkng SystemConnectionStringBooking Details %>" SelectCommand="SELECT Location, Parking_Area, Date_From, Date_To, Parking_Stand, Car_Name, Car_Number, Total_Cost FROM BookingDetail WHERE (Username = @username)" DeleteCommand="DELETE FROM [BookingDetail] WHERE [Booking_id] = @Booking_id" InsertCommand="INSERT INTO [BookingDetail] ([Username], [Location], [Parking_Area], [Date_From], [Date_To], [Parking_Stand], [Car_Name], [Car_Number], [Total_Cost]) VALUES (@Username, @Location, @Parking_Area, @Date_From, @Date_To, @Parking_Stand, @Car_Name, @Car_Number, @Total_Cost)" UpdateCommand="UPDATE [BookingDetail] SET [Username] = @Username, [Location] = @Location, [Parking_Area] = @Parking_Area, [Date_From] = @Date_From, [Date_To] = @Date_To, [Parking_Stand] = @Parking_Stand, [Car_Name] = @Car_Name, [Car_Number] = @Car_Number, [Total_Cost] = @Total_Cost WHERE [Booking_id] = @Booking_id">
        <DeleteParameters>
            <asp:Parameter Name="Booking_id" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="Username" Type="String" />
            <asp:Parameter Name="Location" Type="String" />
            <asp:Parameter Name="Parking_Area" Type="String" />
            <asp:Parameter Name="Date_From" Type="DateTime" />
            <asp:Parameter Name="Date_To" Type="DateTime" />
            <asp:Parameter Name="Parking_Stand" Type="String" />
            <asp:Parameter Name="Car_Name" Type="String" />
            <asp:Parameter Name="Car_Number" Type="String" />
            <asp:Parameter Name="Total_Cost" Type="Int32" />
        </InsertParameters>
        <SelectParameters>
            <asp:SessionParameter Name="username" SessionField="User" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="Username" Type="String" />
            <asp:Parameter Name="Location" Type="String" />
            <asp:Parameter Name="Parking_Area" Type="String" />
            <asp:Parameter Name="Date_From" Type="DateTime" />
            <asp:Parameter Name="Date_To" Type="DateTime" />
            <asp:Parameter Name="Parking_Stand" Type="String" />
            <asp:Parameter Name="Car_Name" Type="String" />
            <asp:Parameter Name="Car_Number" Type="String" />
            <asp:Parameter Name="Total_Cost" Type="Int32" />
            <asp:Parameter Name="Booking_id" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>

    </asp:Content>
